### ISSUE TITLE
Can not init Fiji.app

### ISSUE THREAD

**Issue by EmmaSRH** [akhadangi/Segmentation-Evaluation-after-border-thinning#2]
Thanks for your public code for evaluate vrand and vinfo metrics! But I have some trouble to use this code.

The environment I use is Ubuntu 20.04, python 3.8.8. And pyimagej and scikit-image are installed with pip. I still got the following errors: 

Traceback (most recent call last):
  File "vrand_info.py", line 19, in <module>
    ij = imagej.init('Fiji.app')
  File "/home/srh/anaconda3/lib/python3.8/site-packages/imagej/__init__.py", line 165, in init
    sj.start_jvm()
  File "/home/srh/anaconda3/lib/python3.8/site-packages/scyjava/__init__.py", line 45, in start_jvm
    _, workspace = jgo.resolve_dependencies(
  File "/home/srh/anaconda3/lib/python3.8/site-packages/jgo/jgo.py", line 657, in resolve_dependencies
    mvn = executable_path_or_raise("mvn")
  File "/home/srh/anaconda3/lib/python3.8/site-packages/jgo/jgo.py", line 191, in executable_path_or_raise
    raise ExecutableNotFound(tool, os.getenv("PATH"))
jgo.jgo.ExecutableNotFound: mvn not found on path /home/srh/anaconda3/bin:/home/srh/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/srh/anaconda3/bin

If you have any suggestions please reply in this issue. Thanks!

**Comment by akhadangi** [comment]
Hi,

Thanks for using the code. Seems that you have Maven path issues with your environment. May I ask you please if you can create an environment for imagej and using Conda to install imagej?

https://pypi.org/project/pyimagej/

**Comment by EmmaSRH** [comment]
Dear Afshin,




    Thanks for your timely reply! With your suggestions,  I used Conda to install imagej instead of pip, it finally works! 




    Best Regards.




Ruohua, Shi





-----原始邮件-----
发件人:"Afshin Khadangi" ***@***.***>
发送时间:2021-10-29 17:25:37 (星期五)
收件人: akhadangi/Segmentation-Evaluation-after-border-thinning ***@***.***>
抄送: Emma ***@***.***>, Author ***@***.***>
主题: Re: [akhadangi/Segmentation-Evaluation-after-border-thinning] Can not init Fiji.app (Issue #2)






Hi,

Thanks for using the code. Seems that you have Maven path issues with your environment. May I ask you please if you can create an environment for imagej and using Conda to install imagej?

https://pypi.org/project/pyimagej/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.






        Best Regards.




Shi Ruohua (史若画)

----------------------------------------------------------------


TEL: 15901296112

Email: ***@***.*** / ***@***.*** 
Address: 北京大学理科二号楼2641
